##
## $Id: Makefile,v 1.4 2012-07-20 22:55:54 thor Exp $
##
## Makefile for the j2k transcoder project,
## THOR Software, 2. Jul. 2003, Thomas Richter for
## Pegasus Digital Imaging
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	colortrafo ycbcrtrafo trivialtrafo \
		lslosslesstrafo

DIRNAME	=	colortrafo
SUPER	=	../

include	../Makefile.template
