##
## $Id: Makefile,v 1.6 2012-07-24 19:36:45 thor Exp $
##
## Makefile for the jpeg transcoder project,
## THOR Software, May 20, 2012, Thomas Richter
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	dct idct fdct sermsdct hadamard

DIRNAME	=	dct
SUPER	=	../

include	../Makefile.template
