##
## $Id: Makefile,v 1.13 2015/03/26 07:40:38 thor Exp $
##
## Makefile for the jpeg transcoder project,
## THOR Software, May 20, 2012, Thomas Richter
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	dct idct liftingdct

DIRNAME	=	dct
SUPER	=	../

include	../Makefile.template
