##
## $Id: Makefile,v 1.7 2012-09-15 17:27:27 thor Exp $
##
## Makefile for the jpeg transcoder project,
## THOR Software, May 20, 2012, Thomas Richter
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	dct idct sermsdct hadamard

DIRNAME	=	dct
SUPER	=	../

include	../Makefile.template
