##
## $Id: Makefile,v 1.35 2012-09-28 17:05:21 thor Exp $
##
## Makefile for the jpeg transcoder project,
## THOR Software, May 20, 2012, Thomas Richter
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	encoder decoder tables image entropyparser rectanglerequest \
		sequentialscan acsequentialscan \
		predictivescan losslessscan aclosslessscan \
		refinementscan acrefinementscan \
		hiddenrefinementscan \
		jpeglsscan singlecomponentlsscan lineinterleavedlsscan \
		sampleinterleavedlsscan vesascan vesadctscan

DIRNAME	=	codestream
SUPER	=	../

include	../Makefile.template
