##
## $Id: Makefile,v 1.27 2012-07-29 17:00:39 thor Exp $
##
## Makefile for the jpeg transcoder project,
## THOR Software, May 20, 2012, Thomas Richter
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	encoder decoder tables image entropyparser rectanglerequest \
		sequentialscan differentialscan \
		acsequentialscan acdifferentialsequentialscan \
		losslessscan differentiallosslessscan \
		aclosslessscan acdifferentiallosslessscan \
		refinementscan acrefinementscan \
		residualscan residualhuffmanscan \
		jpeglsscan singlecomponentlsscan lineinterleavedlsscan \
		sampleinterleavedlsscan vesascan

DIRNAME	=	codestream
SUPER	=	../

include	../Makefile.template
