##
## $Id: Makefile,v 1.3 2012-05-20 16:17:27 thor Exp $
##
## Makefile for the jpeg transcoder project,
## THOR Software, May 20, 2012, Thomas Richter
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	upsamplerbase upsampler downsamplerbase downsampler

DIRNAME	=	upsampling
SUPER	=	../

include	../Makefile.template
