##
## $Id: Makefile,v 1.14 2012-09-14 18:22:20 thor Exp $
##
## Makefile for the jpeg transcoder project,
## THOR Software, May 20, 2012, Thomas Richter
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	quantization huffmantable frame component scan \
		adobemarker jfifmarker exifmarker \
		residualmarker losslessmarker tonemappingmarker \
		actable restartintervalmarker scantypes \
		thresholds lscolortrafo residualspecsmarker

DIRNAME	=	marker
SUPER	=	../

include	../Makefile.template
