##
## $Id: Makefile,v 1.15 2014/02/06 16:34:59 thor Exp $
##
## Makefile for the jpeg transcoder project,
## THOR Software, May 20, 2012, Thomas Richter
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	quantization huffmantable frame component scan \
		adobemarker jfifmarker exifmarker \
		actable restartintervalmarker scantypes \
		thresholds lscolortrafo

DIRNAME	=	marker
SUPER	=	../

include	../Makefile.template
