##
## $Id: Makefile,v 1.12 2012-05-20 16:17:27 thor Exp $
##
## Makefile for the jpeg transcoder project,
## THOR Software, May 20, 2012, Thomas Richter
## 
## This sub-makefile includes definitions relative to this
## directory.
##

FILES	=	bitmapctrl residualblockhelper \
		blockbuffer linebuffer \
		blockbitmaprequester linebitmaprequester \
		lineadapter blocklineadapter linelineadapter \
		linemerger hierarchicalbitmaprequester bufferctrl

DIRNAME	=	control

SUPER	=	../

include	../Makefile.template
